### ISSUE TITLE
Bundle all of /app

### ISSUE THREAD

**Issue by probonopd** [sudo-give-me-coffee/flatpak2appdir#12]
I think that we should bundle all of `/app` and not just a subset of it. I am assuming that everything that comes with the app is there for a reason, and hence should be bundled.

Hence, I added in the `deploy-with-appimagetool` branch:

https://github.com/sudo-give-me-coffee/flatpak2appdir/blob/cab8ae0f588dbb805a9db283d508a1096a09a3fc/flatpak2appdir#L109

To my surprise, this breaks things:

```
me@host:~$ '/home/me/Downloads/Text_Editor-3.32.2-x86_64.AppImage'

(gedit:14489): GLib-GIO-ERROR **: 19:37:40.747: Settings schema 'org.gnome.desktop.lockdown' is not installed
Trace/breakpoint trap


me@host:~$ Downloads/Drawing-0.4.13-x86_64\(1\).AppImage 

(com.github.maoschanz.drawing:14543): GLib-GIO-ERROR **: 19:38:21.255: Settings schema 'org.gtk.Settings.ColorChooser' is not installed
Trace/breakpoint trap
```

Do you know why? How to do this correctly?

**Comment by sudo-give-me-coffee** [comment]
The script already do this:

https://github.com/sudo-give-me-coffee/flatpak2appdir/blob/ba7f4610a9cc9a7f1ca6e88466a1defa85cdcb62/flatpak2appdir#L143

Apparently you is overwriting the glib-schemas from runtime

**Comment by sudo-give-me-coffee** [comment]
You need a separate path to glib runtime, i do it a line before copy /app:

https://github.com/sudo-give-me-coffee/flatpak2appdir/blob/ba7f4610a9cc9a7f1ca6e88466a1defa85cdcb62/flatpak2appdir#L143

In next, simply export new path to glib schemas path on AppRun:

https://github.com/sudo-give-me-coffee/flatpak2appdir/blob/ba7f4610a9cc9a7f1ca6e88466a1defa85cdcb62/AppRun#L30

**Comment by probonopd** [comment]
> The script already do this

My mistake, didn't see this. Thank you.
