### ISSUE TITLE
Unquoted paths and variables

### ISSUE THREAD

**Issue by probonopd** [sudo-give-me-coffee/flatpak2appdir#13]
In most places, flatpak2appdir uses unquoted paths and variables, e.g.,

    cp -rf $locale/share/*  ${1}.AppDir/usr/share/locale

instead of 

    cp -rf "${locale}/share/"*  "${1}.AppDir/usr/share/locale"

Are missing quotes are causing e.g., XPS Office to fail?

Build log:
https://travis-ci.org/github/sudo-give-me-coffee/flatpak2appdir/jobs/664973306

**Comment by sudo-give-me-coffee** [comment]
I will add this

**Comment by sudo-give-me-coffee** [comment]
But these paths generally has no spaces, i will try WPS manually

**Comment by sudo-give-me-coffee** [comment]
WPS Office over Flatpak is outdated...

**Comment by probonopd** [comment]
OK, then let's remove WPS Office for now from our tests. Still I think quoting is a good idea in bash. Do you know https://www.shellcheck.net/?

**Comment by probonopd** [comment]
Related question, do you plan to keep this as a shell script forever or do you plan to go to a compiled language at some point, e.g., Golang?

**Comment by sudo-give-me-coffee** [comment]
No, i'm thinking to rewrite using `lua`

**Comment by sudo-give-me-coffee** [comment]
Done in https://github.com/sudo-give-me-coffee/flatpak2appdir/commit/66eed778232d68f894fa351b32a4c16a29f75f75
