### ISSUE TITLE
Gtk theming

### ISSUE THREAD

**Issue by probonopd** [sudo-give-me-coffee/flatpak2appdir#8]
On some systems, the current way to handle Gtk themes seems to be working great because the applications look native. Here is the Drawing app on Xubuntu 18.04, looks native.

![wow](https://user-images.githubusercontent.com/2480569/77144437-cb26df00-6a7d-11ea-88d9-211a5a93ae12.png)

However, in other situations, theming is entirely broken.

Maybe the way to go would be to bundle the theme from Flatpak, and then decide at runtime whether to use the system one or the bundled one. E.g., if the system one is much older than the bundled one, then use the bundled one; use the system one otherwise.

What do you think?

**Comment by sudo-give-me-coffee** [comment]
Is a very good idea, but i don't know how to implement this, maybe checking glibc version?

**Comment by sudo-give-me-coffee** [comment]
These applications (if the conversion is successful) runs even on Ubuntu 12.04

**Comment by probonopd** [comment]
> Is a very good idea, but i don't know how to implement this, maybe checking glibc version?

I was thinking of checking the Gtk version.

**Comment by sudo-give-me-coffee** [comment]
I'm added this option on https://github.com/sudo-give-me-coffee/flatpak2appdir/commit/4eb33ec4fae1639b07cf9a402c118b1ca45a0e52
